Parameters:
  ProjectName:
    Description: Project name
    Type: String
    Default: appmeshdemo
  DBName:
    Description: The database name
    Type: String
    MinLength: '1'
    MaxLength: '64'
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: must begin with a letter and contain only alphanumeric characters.
  DBUser:
    Description: The database admin account username
    Type: String
  DBPassword:
    Description: The database admin account password
    Type: String
  DBAllocatedStorage:
    Default: '5'
    Description: The size of the database (Gb)
    Type: Number
    MinValue: '5'
    MaxValue: '1024'
    ConstraintDescription: must be between 5 and 1024Gb.
  DBInstanceClass:
    Description: The database instance type
    Type: String
    Default: db.t2.small  
Resources:
  RDSInstanceSecurityGroup:
      Type: AWS::EC2::SecurityGroup
      Properties:
        GroupDescription: RDS Securitygroup
        VpcId: 
          Fn::ImportValue: !Sub '${ProjectName}:VPC' 
        SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '3306'
          ToPort: '3306'
          SourceSecurityGroupId: 
            Fn::ImportValue: !Sub '${ProjectName}:BastionSecurityGroup'
        - IpProtocol: tcp
          FromPort: '3306'
          ToPort: '3306'
          SourceSecurityGroupId: 
            Fn::ImportValue: !Sub '${ProjectName}:TaskSecurityGroup'
       
            
  RDSSubnetGroup: 
    Type: AWS::RDS::DBSubnetGroup
    Properties: 
      DBSubnetGroupDescription: Subnet group for the RDS Instance
      SubnetIds: 
        - Fn::ImportValue: !Sub '${ProjectName}:PrivateSubnet1' 
        - Fn::ImportValue: !Sub '${ProjectName}:PrivateSubnet2' 
  RDSInstance:
    Type: AWS::RDS::DBInstance
    DependsOn: RDSSubnetGroup
    Properties:
      DBName: !Ref DBName
      AllocatedStorage: !Ref DBAllocatedStorage
      DBInstanceClass: !Ref DBInstanceClass
      DBSubnetGroupName: !Ref RDSSubnetGroup
      Engine: MySQL
      MasterUsername: !Ref 'DBUser'
      BackupRetentionPeriod: 0
      MasterUserPassword: !Ref 'DBPassword'
      VPCSecurityGroups: 
      - !Ref RDSInstanceSecurityGroup
Outputs:
  RDSJDBCString:
    Description: RDS JDBC String
    Value: !Join ['', ['jdbc:mysql://', !GetAtt [RDSInstance, Endpoint.Address], ':', !GetAtt [RDSInstance, Endpoint.Port], /, !Ref 'DBName']]
    Export: 
      Name: !Sub '${ProjectName}:RDSJDBCString'
  RDSEndPoint:
    Description: RDS DNS Endpoint
    Value: !GetAtt [RDSInstance, Endpoint.Address]
    Export:
      Name: !Sub '${ProjectName}:RDSEndpoint'